sudo: required
services:
  - docker

before_install:
  - docker pull node:8-onbuild

install:
  - docker build -t probot-hello .

script:
  - docker run --rm probot-hello npm run test

after_success:
  - docker tag probot-hello probot-hello:$(git rev-parse HEAD) #This hashes and gives unique tag to save this container for later..
